server:
  port:
    8081
spring:
  application:
    name: file
  data:
    mongodb:
      host: localhost
      port: 27017
      database: files
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB