server:
  port:
    8082
spring:
  application:
    name: music
  datasource:
    url: jdbc:postgresql://localhost:5432/listenloud_music
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB